### ISSUE TITLE
Lichtgeschwindigkeit compatibility

### ISSUE THREAD

**Issue by dev7355608** [David-Zvekic/TokensVisible#13]
The [Lichtgeschwindigkeit](https://github.com/manuelVo/foundryvtt-lichtgeschwindigkeit) module replaces the sight computation. I haven't tested it extensively, but it seems that these changes make the ray/sight optimization options that Your Tokens Visible provides unnecessary and could potentially conflict. It's probably best that Your Tokens Visible disables those optimization options when Lichtgeschwindigkeit is loaded, and doesn't touch the sight computation code at all, I suppose.

**Comment by David-Zvekic** [comment]
TokensVisible uses libwrapper library so that other module writers could
use that to force their modules to override the sight computation rather
than TokensVisible.

ideally lichtgeshwindigkeit would also use libwrapper library so that GMs
can control which module can override that function.

I'll investigate it however. thanks for bringing it to my attention.

**Comment by dev7355608** [comment]
libWrapper is probably a good idea, but the only thing the Lichtgeschwindigkeit does is to replace the sight computation code. So I assume it would be always preferable to yield to this module and not letting the user resolve this conflict manually (if they didn't want Lichtgeschwindigkeit, they would disable the entire module).

They seem to work together at the moment in FVTT 0.8, because Tokens Visible still patches the deprecated `SightLayer.computeSight` function and not `WallsLayer.prototype.computePolygon`, which has the effect that TokensVisible's Sight Calculations Cache feature isn't working in FVTT 0.8+ as far as I can tell. When I corrected that Lichtgeschwindigkeit didn't work (I disabled all optimization options in TokensVisible).

**Comment by manuelVo** [comment]
The function `tokensVisible.SightLayer._turboComputeSight` is registered in libwrapper as `OVERRIDE` (which indicates that it'll never call the original function), but [sometimes it actually calls the original function](https://github.com/David-Zvekic/TokensVisible/blob/2726cd8c1936eeea53f3c870127c34572c325a32/TokensVisible.js#L499). Instead, the function should be registered as `MIXED`, leaving the decision which function to call next to libwrapper. Additionally, [I don't think it's necessary to re-register the original `computeSight` function as wrapper for itself](https://github.com/David-Zvekic/TokensVisible/blob/2726cd8c1936eeea53f3c870127c34572c325a32/TokensVisible.js#L517). libwrapper should take care of that when the existing wrapper is being unregistered. 

If those two things are done, TokenVision and Lichtgeschwindigkeit should be compatible.

It's worth noting that if both TokenVision and Lichtgeschwindigkeit are installed, TokenVision's Ray Casting mode settings are going to be ignored (because Lichtgeschwindigkeit completely replaces the `computeSight` function and will never call `castRays` so it might be a good idea to detect if Lichtgeschwindigkeit is running and not show that setting to the user in that case.

**Comment by David-Zvekic** [comment]
as far as I can tell in my testing, this module is now compatible with Lichtgeschwindigkeit.  

Thanks for the information.
