### ISSUE TITLE
bug: vision not updating when opening door

### ISSUE THREAD

**Issue by Shenanigan83** [David-Zvekic/TokensVisible#17]
When a PC open a door. it doesnt update vision, you need to enter the room to make the fog of war disappear.  I disabled the module and it works as intended. so there's something about the module that prevent showing the opened room

**Comment by David-Zvekic** [comment]
I just re-tested this again in 0.8.8 and 0.7.10 on alienrpg and Dnd5e.
This works properly with Your Tokens Visible alone or in combination with
my other modules. (I use 38 other modules)
It's possible that Your Tokens Visible is not compatible with the game
system you are using or another module you are using.

Try turning all the other modules off. If that fixes it, then try adding
them back 1 at a time until the problem re-appears.

Failing all that, try turning off the Sight Update Cache and changing the
Ray Casting Precision mode to 'Standard'.

If you tell me which game system you are using and I can replicate it, I
may be able to find a workaround but at this time I cannot replicate this
issue.

**Comment by Shenanigan83** [comment]
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:72.0pt 72.0pt 72.0pt 72.0pt;}
div.WordSection1
	{page:WordSection1;}

**Comment by David-Zvekic** [comment]
I have confirmed this module is not compatible with PF2e
PF2e creates its own vision rules that wont see some things Your Tokens Visible does.

If turning off the Sight Calculation Cache works then I would just do that.   The performance benefit in foundry 0.8 is now minimal anyway.  Since this is a player setting, advise your players to also disable it in their system settings.

In a future version this feature will default to OFF for foundry 0.8 due to the minimal benefit. in 0.7 it speeds up certain operations very noticibly.

**Comment by dev7355608** [comment]
I can reproduce this issue in FVTT 0.8.8 / DnD 5e 1.3.6 / Tokens Visible 2.5.0 / Sight Cache: ON with no other modules enabled. No issues if sight caching is turned off.

**Comment by David-Zvekic** [comment]
seems you are right. it actually happens intermittantly in 0.8.8 even in
alienrpg and dnd5e but I didn't notice because lichgeschwindigkeit was
installed in my 0.8.8 environment and that bypasses Castrays completely and
does its own type of calculation.   In my PF testing I specifically had all
other modules turned off.

Please try 2.5.1.   It may even work in pathfinder now. (in my testing it
seems to work in pathfinder)

**Comment by Shenanigan83** [comment]
I updated to version 2.5.1 and enabled cache ON  and it works  in pf2e. You seem to have fixed it :)  thanks
