### ISSUE TITLE
Feature Request - Disable Automatic Panning

### ISSUE THREAD

**Issue by friction1** [David-Zvekic/TokensVisible#2]
This module is awesome, thanks so much for your work. Can you please make the automatic edge panning toggle able? My players want to have the option to turn it off. Setting the value to 0 does not appear to turn it off.

**Comment by David-Zvekic** [comment]
Can you clarify?  What do your players want to happen when their token
tries to walk off the edge of the canvas?  Does it block them from walking
more, or does it let them keep walking even though they can't see where
they are going?

FYI: the core system auto recenters at 50 pixels.  Setting this to 0 would
simply let someone get closer to the edge before triggering pan-to-centre.

**Comment by friction1** [comment]
Thank for you the reply. I guess we never noticed the recentering before using the module but i think what you’re describing makes sense. Is there a way to have the map view move by 1 square when you move off the map instead of recentering? I realize this may be beyond the scope of what you were trying to accomplish.

**Comment by friction1** [comment]
I just tested it again. It seems like auto-recenter without the module only occurs when you try to move within 1 square of the edge of the map. When your module is enabled, even when I have the Automatica Pan Margin set to 0, when a player drops a token within like 5 squares of the edge of the map, it re-pans to center. 

Here's a video: https://www.dropbox.com/s/bjei8880uncfoca/screen%20recording.mov?dl=0

**Comment by David-Zvekic** [comment]
I notice you said that when "I" have it set to 0, then a "player" drops a
token....

did you confirm that the player has set his or her personal preferences?
 this is a client side setting - the GM does not control it for players.

I actually am working on an alternative mode which is that the map only
scrolls as much as needed to re-cover the margin, rather than re-centre.
This is a bit more complicated because the API is set up to require you to
tell it what to center on (basically -- centre on the centre of the token
and boom).   You can't simply say 'move 100 pixels to the right'.  You
can't even directly ask it where it is currently centered... you have to
calculate what it was centered on based on zoom factor and the top left
edge and the total canvas size and the screen resolution, then calculate a
new position to centre on, and then centre on that.  I made the mistake of
under-estimating the complexity and spent 2 hours confusing myself...
 after I get some proper sleep I should be able to do it.

There will then be 2 modes : automatic pan (recenter on token).  Automatic
pan (scroll as-needed).   ...  or some name like that.

**Comment by friction1** [comment]
I did not realize players can control their own number. That should solve their problem! Thank you very much for the help! Issue resolved.
