### ISSUE TITLE
Some compatibility issue with Drag Ruler

### ISSUE THREAD

**Issue by thatlonelybugbear** [David-Zvekic/TokensVisible#21]
Using YTV (v2.5.2) Drag Ruler (v1.7.7) on Foundry 0.8.8, and with the option for walls to cancel animation checked.

As a GM when you drag a token over a wall the animation is cancelled, but the ruler that appears when you drag the token is visible for the duration that the actual move would have taken.

If you right click while the token is moving, the drag ruler disappears and from that moment onwards, for the selected token the drag ruler vanishes as intended (now and then when you pick up the token and move it a bit fast the movement is not registered at all though as a side issue).

If you choose another token at any point or deselect the first token, the same issue appears again and so on.

In the video the aforementioned behaviour is shown and just before I start moving the tokens around rapidly, I have right clicked to make the drag ruler template disappear faster.

https://user-images.githubusercontent.com/7237090/125272335-a1916700-e303-11eb-9c53-b685e277f520.mp4

Not sure if this is a Tokens Visible or Drag Ruler issue. Think that another issue with these two modules I raised on Foundry discord was addressed with a YTV update though, so I post it here first.

**Comment by David-Zvekic** [comment]
I would report this issue to Drag Ruler.

Drag Ruler draws and erases the ruler, not YTV.
Drag Ruler should probably wrap Token.prototype.setPosition if it wants to
guarantee that the duration of the ruler rendering always matches the
duration of the animation rather than assuming a duration.
After setPosition returns then the animation is complete.

**Comment by manuelVo** [comment]
This bug does also occur in "Your Tokens Visible" when Drag Ruler is disabled when moving the token via Measure+Spacebar, meaning Drag Ruler doesn't have anything to do with this bug occuring.

**Comment by David-Zvekic** [comment]
I'll look at your report of the "bug" without drag ruler, because you are
changing your report and now reporting that there is no dependence on Drag
Ruler.

"As a GM when you drag a token over a wall the animation is cancelled, but
the ruler that appears when you drag the token is visible for the duration
that the actual move would have taken."

That issue is caused by Drag Ruler, making assumptions of the animation
time.   Without Drag Ruler, using core system, as a GM if you attempt to
draw a ruler path that crosses a wall, Foundry cancels the entire movement
and gives you an error that the movement path crosses a wall.  This happens
with or without YTV.   When you do a valid ruler-token-movement without
Drag Ruler, the ruler rendering in the base Foundry system exactly matches
the travel time of the token.

"If you right click while the token is moving, the drag ruler disappears
and from that moment onwards, for the selected token the drag ruler
vanishes as intended (now and then when you pick up the token and move it a
bit fast the movement is not registered at all though as a side issue)."

What you describe is standard behavior, with or without YTV.  attempting to
move the token before its current token-movement is complete, moves the
token from it's current position to the new position immediately - Foundry
does not let the current movement finish.  Right clicking a token movement
along a ruler, causes the rule to vanish immediately (with or without YTV).

**Comment by manuelVo** [comment]
Please note that the comment that "changed" the bug report wasn't made by the person who initially reported the issue. I'm the author of Drag Ruler and left that comment because I closed this issue in my repository because I don't consider Drag Ruler to be at fault for this behavior and wanted to let you know about this. My explanation of why I think this is the case was rather brief and I'll elaborate a bit further on why I think that:

Generally, Drag Ruler replicates the behavior of the Measure+Spacebar movement scheme. For one Measure+Spacebar does already do roughly the right thing and additionally doing things this way reduces the likelyhood of module conflicts, because modules that work well with Foundry Cores Measure+Spacebar functionality are very likely to work well with Drag Ruler too. As a result should you decide to fix the compatibility with Measure+Spacebar, the issue presented here with Drag Ruler will very likely go away as well. That's why I consider this not to be a bug in Drag Ruler.

Additionally I'd like to state that Drag Ruler doesn't make any assumptions about the animation time. It simply calls `Token.animateMovement` and `await`s that fucntions completion. After that function returns, the Ruler is being cleared. If the animation is cancelled properly (if it isn't this might be a core foundry as well - [this has happened in the past](https://gitlab.com/foundrynet/foundryvtt/-/issues/4902)) that would be a possible explanation for the behavior described in this issue.

**Comment by thatlonelybugbear** [comment]
Indeed, I didn't change my initial report at any point but instead reported the issue to the Drag Ruler git as instructed.

PS1: Tbh I cannot reproduce the extra issue manuelVo mentioned as when I am trying to move a token with just Measure+Spacebar over a wall, the wall doesn't allow the move. Maybe I misread the comment, will take another look.

PS2: I am taking a look at how another module (Monks Little Details) cancels the movement when you press a specific key. There are no issues when this module cancels the movement with the Drag Ruler being cleared immediately.

**Comment by David-Zvekic** [comment]
I looked at Monks LIttle Details method but that method doesn't work because by the time the YTV code fires, Drag Ruler has already called animateMovement asynronously and is waiting for the promise (which is simply pending because javascript it not really asynchronous).

This however gave me an idea, and 2.5.3 should fix it.

Since setPosition is the last method called, and it awaits animateMovement, and YTV is also wrapping animateLinear (for the ability to change animation speed), this means YTV can decide to set the duration to 0 temporarily for ANY token animation that happens after it calls await.   this 'await' call then allows all the promises to be animated which are then set to 0 duration (because they depend on the YTV wrapped animateLinear.  Subsequently the Drag Ruler vanishes as the User expects.

uploading 2.5.3 now.

**Comment by thatlonelybugbear** [comment]
Works like a charm! Nice one, thanks
