### ISSUE TITLE
Console error when logging in

### ISSUE THREAD

**Issue by uniwars** [David-Zvekic/TokensVisible#24]
Hello, here an error I think comes from YTV (TokensVisible is mentionned)

![image](https://user-images.githubusercontent.com/65986545/127506875-58ab5cea-f79a-435b-bf45-daf057f9a805.png)

**Comment by David-Zvekic** [comment]
Thank you for your report.
It looks like a possible conflict between Pathfinder, a module called
wall-height, and YTV.

can you provide me the following information:

Foundry Version
Game system and version
Your Tokens Visible version.
other active modules and and their versions.

important: Steps to replicate this error.

If I can replicate the error then I can investigate it, otherwise perhaps
other users will have additional information to replicate the error.

Thanks again!

**Comment by uniwars** [comment]
After deactivating/reactivating YTV all the errors are gone and I can't make them back, so I think it's fixed

**Comment by David-Zvekic** [comment]
thanks.  there might be some very specific edge case that occurs if and
only if someone installs a combination of modules in a particular order.
Since it went away and we can't reproduce this, we'll just have to leave it
for now.
