### ISSUE TITLE
Game settings are not registered at the right time?

### ISSUE THREAD

**Issue by shemetz** [David-Zvekic/TokensVisible#3]
When loading a world with this module, I constantly get this error:
```js
foundry.js:2499 Error: This is not a registered game setting
    at ClientSettings.get (foundry.js:3436)
    at TokensVisible.js:350
    at Function._call (foundry.js:2496)
    at Function.call (foundry.js:2481)
    at SceneControls._render (foundry.js:4547)
```

referring to the line: `game.settings.get('TokensVisible', 'toggleActiveBG')`

I looked at the code and it seems like you are calling all of the `game.settings.register` functions at the top-level of the module.

I think you should instead register them inside `Hooks.on('init',() => {...})` - this is how other modules do it and it seems to always work there.

**Comment by David-Zvekic** [comment]
Hi Thanks for your feedback.
I haven't experienced any issues and noone else reported it,  however it
may be that once a setting exists, then subsequent loads of the module will
not get that errror because the setting will become part of the world JSON.

In any case the latest version I've been working on moves the settings
registration to Hooks.on('init') anyway.   I didn't push it up because it
has no difference in behavior (or at least I didn't think it does), but
maybe it will solve your issue?
Can you tell me if it resolves your issue?  I have not been able to
replicate your issue.
