### ISSUE TITLE
[Feature Request] Change manifest URL to non changing address

### ISSUE THREAD

**Issue by DanielBoettner** [David-Zvekic/TokensVisible#31]
Hello @David-Zvekic,

I would like to suggest to change this 
https://github.com/David-Zvekic/TokensVisible/blob/74289d84d18f5ce4ad62e42327e0e5aed298612c/module.json#L10

to
 
```json
"manifest": "https://raw.githubusercontent.com/David-Zvekic/TokensVisible/main/module.json", 
```

## Why

Having the manifest URL change on version bumps is interrupting bulk update in FoundryVTT's setup.
The user has to confirm the change, which is good because for security reasons.
However, because of the version number in the manifest, even minor patches x.x.1 would need confirmation.

## Benefits of changing to branch name in url

* Updates on main (or a dedicated release branch) would be available instantly (afaik)
  * a release via Foundry website is still needed to show up with the proper version there.
* The module updates without a manual confirmation needed.
* users can still manually get the previous releases from github
  * or via the actions, you could create a merge of main to a specific version branch 
  * could place the current placing of the version in these "backup" branch. So user can actually stay on that "stable"/"old" branch.

**Comment by David-Zvekic** [comment]
Thank you for your feedback.
Yes you are right about security. If someone hacks a Github account and
installs a malicious module.json and causes everyones VTT to update without
confirmation at the very minimum they could obliterate hundreds of years of
world specific campaign data across many gaming groups if the GM wasn't
keeping backups.

I dont think I'll do this.

I understand that the specification of module.json is to include a path to
the specific manifest, rather than a pointer to the manifest for the latest
version.

If that is the case I don't believe that a module author should use an
undocumented side effect to bypass the foundry confirmation feature.
The option to skip confirming multiple confirmation forms on updating
modules could actually fall within Foundry VTT itself via a "Confirm All"
button.  Maybe you might want to suggest it to the Foundry core dev?
