### ISSUE TITLE
0.8.6: vision not updated for player token when GM moves it

### ISSUE THREAD

**Issue by wmve** [David-Zvekic/TokensVisible#9]
i moved this token into the hallway **_from the GM console_** where there is light, but token can't see down the hall
![image](https://user-images.githubusercontent.com/55966777/120872918-15ef2280-c56e-11eb-9f91-cb42051a7831.png)

i moved the token one square north **_from a player session_** in a browser and now the token can see down the hall
![image](https://user-images.githubusercontent.com/55966777/120872886-fce67180-c56d-11eb-86fb-5104b175d534.png)

versions:
![image](https://user-images.githubusercontent.com/55966777/120872982-5353b000-c56e-11eb-8431-9ec532ae5f42.png)

i got this error when loading the session on the foundry console
![image](https://user-images.githubusercontent.com/55966777/120873012-6ebebb00-c56e-11eb-865a-cc5295f56c55.png)

here's the errors i see in the console, but the red ones just look like missing art files
![image](https://user-images.githubusercontent.com/55966777/120873057-96ae1e80-c56e-11eb-97f2-752082bb4064.png)

here's the json of the character in question
[fvtt-Actor-hillgaard.210604.zip](https://github.com/David-Zvekic/TokensVisible/files/6601683/fvtt-Actor-hillgaard.210604.zip)

**Comment by David-Zvekic** [comment]
Your Tokens Visible hasn't been updated for FoundryVTT 0.8.x yet.   it
isn't compatible because it replaces some core functionality of FoundryVTT
0.7.9.
Try disabling the Raycasting Cache and use standard Ray Casting mode.  That
may let other parts of the module function. (but I haven't tested it).

When the module is ready for 8.x there will be a new version. Right now it
officially supports 0.7.9 only.

Thanks for the feedback. The information will help me know what kinds of
incompatibilities I need to search for.

Davd Z

**Comment by wmve** [comment]
will do.  i'm **_really_** looking forward to the update.  i went looking for a module like yours because i hated player tokens look between walls as i move them across a map.  nice work.  waiting with bated breath!  :)

**Comment by David-Zvekic** [comment]
In my testing so far the following settings appear to work in 0.8.6.  I
can't replicate your precise problem.

Combat Tracker Initial Visibility: Use standard Foundry behavior.
(MANDATORY)
Push Token Back - Hokey --- WORKS NORMALLY
Active-Toggle Controls pen-color :WORKS NORMALLY
Active-Toggle Controls background-color: WORKS NORMALLY
Active Control pen-color: WORKS NORMALLY
Active Control background-color: WORKS NORMALLY
Automatic Pan Mode: WORKS NORMALLY
Automatic Pan Margin: WORKS NORMALLY
Token Light: WORKS NORMALLY
Animation during GM Movement : WORKS NORMALLY
Ray Casting Precision Mode : Standard Built in Function   (MANDATORY)
Ray Casting Toggle Hotkey : --- probably works, but MOOT since Ray Casting
Precision Mode itself is broken and only 1 mode works now.
Sight Calculations Cache:    Maybe works... maybe doesn't.  I'm not seeing
any difference in behavior on my systems, but see libwrapper note below.
Sight Calculations Cache Toggle Hotkey : WORKS NORMALLY

I've also noticed Libwrapper becomes more essential... it doesn't seem
optional as it is in 0.7.9. Part of the libwrapper so-called "shiv" may
have become incompatible so make sure to install Libwrapper.

After installing Libwrapper can you try these settings?:

Combat Tracker Initial Visibility: Use standard Foundry behavior.
Ray Casting Precision Mode : Standard Built in Function
Sight Calculations Cache:  Cache is OFF

After that please tell me if you still have the issue you found.  I can't
replicate your exact reported problem. If you can confirm then I can put a
note in the README file to help people for the time being.

Your Tokens Visible is not fully compatible with 0.8.6 but until it's updated,
maybe the above can work and only lose 1 feature that isn't merely a
performance boost.

Thanks for any help.
David Z

**Comment by wmve** [comment]
i think i've reproduced the behaviour with those settings with the player session in chrome.  

![image](https://user-images.githubusercontent.com/55966777/120952776-b33a8a00-c719-11eb-90fa-3af990f3860b.png)

before GM moves token through walls
![image](https://user-images.githubusercontent.com/55966777/120953015-2e9c3b80-c71a-11eb-9f16-e785f902b1ff.png)
after GM moves token through wall
![image](https://user-images.githubusercontent.com/55966777/120953023-322fc280-c71a-11eb-8a23-e54989c48240.png)
after player move token one space it updates to correct vision and lighting
![image](https://user-images.githubusercontent.com/55966777/120953027-34921c80-c71a-11eb-83d4-c975cefb6f80.png)

without moving through walls, extensive testing showed that moving the token through the door and only along the row of spaces the highlighted token is on also shows the same behaviour.  other starting or ending positions usually didn't come up with the same (unexpected) result.

in this case from out in the hallway with the rest of the party
![image](https://user-images.githubusercontent.com/55966777/120953539-25f83500-c71b-11eb-9b5f-28e661dfb8c3.png)

in this case from that same place next to the black & white badger back to where the party is (original location)
![image](https://user-images.githubusercontent.com/55966777/120953592-458f5d80-c71b-11eb-8233-b06e56546319.png)

in both cases, correct vision is restored by token being moved one or two squares by EITHER the player or GM.

i'll attach json of the scene and in addition to the actor in case that helps.
my repro, just to be clear, is in watching the player session of a player who is matched to the token in question
[fvtt-Scene-portal-chambers-1.210606.zip](https://github.com/David-Zvekic/TokensVisible/files/6605588/fvtt-Scene-portal-chambers-1.210606.zip)

**Comment by David-Zvekic** [comment]
version Your Tokens Visible 2.0.0 should fix it.    Please confirm.

**Comment by wmve** [comment]
yes!  confirmed, thank you!

**Comment by David-Zvekic** [comment]
thank you. I'm closing this issue.
